apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: vallerion/hellok8s:0.6.3
          name: hellok8s-container
          resources:
            requests:
              cpu: 500m
              memory: 5Mi

---

apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
    - port: 8081
      nodePort: 30001