apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
    - port: 8081
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      volumes:
        - name: config
          configMap:
            name: hellok8s-config
      containers:
        - image: vallerion/hellok8s:0.5
          name: hellok8s-container
          volumeMounts:
            - mountPath: /config
              name: config
          envFrom:
            - prefix: CONFIG_
              configMapRef:
                name: hellok8s-config
#          env:
#            - name: MESSAGE
#              value: "MESSAGE FROM K8S ENV"
#              valueFrom:
#                configMapKeyRef:
#                  key: MESSAGE
#                  name: hellok8s-config