apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  strategy:
    type: Recreate
  replicas: 10
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: vallerion/k8s-cource-1:1.02
          name: hellok8s-container
