apiVersion: apps/v1
kind: Deployment
metadata:
  name: num
spec:
  replicas: 2
  selector:
    matchLabels:
      app: num
  template:
    metadata:
      labels:
        app: num
    spec:
      containers:
        - image: vallerion/num:0.2
          name: num-container
          readinessProbe:
            periodSeconds: 1
            successThreshold: 5
            httpGet:
              path: /health
              port: 8081
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /health
              port: 8081
          resources:
            requests:
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: num-svc
spec:
  type: NodePort
  selector:
    app: num
  ports:
    - port: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: num-hop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: num
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50