apiVersion: apps/v1
kind: Deployment
metadata:
  name: loop
spec:
  selector:
    matchLabels:
      app: loop
  template:
    metadata:
      labels:
        app: loop
    spec:
      containers:
        - image: vallerion/loop:0.1
          name: loop-container
          resources:
            requests:
              cpu: 6500m
              memory: 5Mi