apiVersion: apps/v1
kind: Deployment
metadata:
  name: num
spec:
  replicas: 2
  selector:
    matchLabels:
      app: num
  template:
    metadata:
      labels:
        app: num
    spec:
      containers:
        - image: vallerion/num:0.1-amd64
          name: num-container

---

apiVersion: v1
kind: Service
metadata:
  name: num-svc
spec:
  type: NodePort
  selector:
    app: num
  ports:
    - port: 8081