apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: vallerion/hellok8s:0.3
          name: hellok8s-container
          readinessProbe:
            periodSeconds: 1
            successThreshold: 5
            httpGet:
              path: /health
              port: 8081
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /health
              port: 8081
