apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
  namespace: taras
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
        - image: vallerion/hellok8s:0.5
          name: hellok8s-container

---

apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
  namespace: taras
spec:
  type: NodePort
  selector:
    app: hellok8s
  ports:
    - port: 8081
#      nodePort: 30001